version: "2"         # required to adjust maintainability checks

exclude_patterns:
  - "**Tests/"
  - PDFArchiver/Helpers/Payment/SwiftyLocalReceiptValidator.swift

checks:
  method-complexity:
    config:
      threshold: 10
