language: swift
os: osx
osx_image: xcode9.4

before_install:
  - brew bundle
  - gem install xcpretty

install:
  - bash $TRAVIS_BUILD_DIR/scripts/build_openssl.sh

script:
  - swiftlint
  - xcodebuild clean test -project "PDFArchiver.xcodeproj" -scheme "PDFArchiver" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty && exit ${PIPESTATUS[0]}

notifications:
  email:
    on_success: never
    on_failure: change
