language: swift

os: osx

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

osx_image:
  - xcode8.3
  - xcode9.2
  - xcode9.3beta

script:
  - swiftlint
  - xcodebuild test -project "PDF Archiver.xcodeproj" -scheme "PDF Archiver"

notifications:
  email:
    on_success: never
    on_failure: change
