language: swift
os: osx

before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint

osx_image: xcode9.2

script:
  - swiftlint
  - xcodebuild clean test -project "PDF Archiver.xcodeproj" -scheme "PDF Archiver" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
notifications:
  email:
    on_success: never
    on_failure: change
